### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by mmmwhy** [li-xirong/coco-cn#12]
I've applied several times and no one has replied, my email is  mmmwhy#mail.ustc.edu.cn (replace # as @)

**Comment by mmmwhy** [comment]
I found this dataset, not sure if it is the dataset referred to in the README.
![image](https://user-images.githubusercontent.com/11297491/118229231-3d4a5680-b4be-11eb-847a-4c50cbe8145e.png)

**Comment by li-xirong** [comment]
yes

**Comment by mmmwhy** [comment]
thanks
