### ISSUE TITLE
Request for JSON files

### ISSUE THREAD

**Issue by hgzjy25** [li-xirong/coco-cn#13]
I have already get this coco-cn dataset, but I find that two json file **dataset_mscoco-cn.json** and **captions_mscoco-cn.json** mentioned in README.md in coco-cn_caption directory is missing. And the download link you provided in issues is invalid now. So I request a new download link for these files. Thanks!

**Comment by li-xirong** [comment]
hi, the implementation provided in the coco-cn_caption folder  is no longer state-of-the-art. We plan to upgrade the code. At the moment, we suggest you adapt the coco-cn dataset with respect to your own image captioning code.
