### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by Hanzhanghub** [li-xirong/coco-cn#2]
Hello, thanks for releasing the great work.
Sorry to bother you, but when I check the released json file, I have two questions:

- a. There is no tags in any json file,  where can I find the tags like it presented in the paper ?

- b. There is 19165 images (smaller than 20342) in _captions_mscoco-cn.json_, is this json file a final version？

Thanks for your reply!

**Comment by yueranjzx** [comment]
Hello, it's true that the json files are not the latest version. The tag data and latest captioning data (in raw text format) are available at  [this link](https://pan.baidu.com/s/1g44fXvjlGceVFTWNsiFrBQ), the corresponding extraction code is yycn.

**Comment by Hanzhanghub** [comment]
Thank you!
