### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by TalentWong** [li-xirong/coco-cn#21]
Hi, I'm a Ph.D. student, and I have read your paper(it is an excellent work). So I'm going to do some research based on your  COCO-cn dataset. And I have submitted the COCO-CN Application Form 5 days ago. There's no response now, so I hope you can quickly pass the audit. Many thanks!

**Comment by li-xirong** [comment]
hi, plz specify properly your university and re-submit the form. See also https://github.com/li-xirong/coco-cn/issues/19

**Comment by TalentWong** [comment]
Thanks for the reply. I have already specified my university on the last form in the 'Purpose of using COCO-CN' part. Maybe it is not obvious. I submitted the form again and specified the university in the 'Affiliation' part. I'm looking forward to your audit.
