### ISSUE TITLE
coco-cn dataset

### ISSUE THREAD

**Issue by Xiong-can** [li-xirong/coco-cn#29]
Hello, thank you for your great work!! I have applied for the COCO-CN dataset but received no reply.
my email: 2641995902@qq.ccom

**Comment by li-xirong** [comment]
hi, please submit your dataset request using your **_institutional-domain_** email address.

**Comment by Xiong-can** [comment]
> hi, please submit your dataset request using your **_institutional-domain_** email address.

xiongcan@mails.ccnu.edu.cn，thanks！

**Comment by Weifeng-Chen** [comment]
> > hi, please submit your dataset request using your **_institutional-domain_** email address.
> 
> [xiongcan@mails.ccnu.edu.cn](mailto:xiongcan@mails.ccnu.edu.cn)，thanks！

Hi! Can you send me the dataset, I have applied for it but still no reply. My email is chenwf35@mail2.sysu.edu.cn
