### ISSUE TITLE
Requests for dataset

### ISSUE THREAD

**Issue by Androgyne** [li-xirong/coco-cn#42]
Hello! I've filled out the Google form requesting the dataset. I'm looking forward to your reply. Thanks!!!
And my email address is tianzhili@zju.edu.cn

**Comment by gzwo-O** [comment]
I have already filled out the Google form, yet I haven't received a reply from the author so far. I'm writing to inquire whether you could be so kind as to send me the download link of the dataset. I'd like to assure you that I will only use this dataset for academic purposes.
My student email address is gaozhenwei@std.uestc.edu.cn.
Thank you very much for your help!
![76f697e50a5d7270702e1ab4ca5194d140e2b992](https://github.com/user-attachments/assets/04a985b1-0dd5-4f66-97ce-1e0cfc18c242)
