### ISSUE TITLE
关于数据集的图片

### ISSUE THREAD

**Issue by Eve-Wang** [li-xirong/coco-cn#45]
你好，我已经通过邮件获得了你们的中文标注数据，非常感谢。但关于图片一直没有找到一个下载通道，请问能否提供一个下载链接

**Comment by gzwo-O** [comment]
您好 我已经填写了google表单 但是作者目前还没有回复 请问您能帮我发一下数据集的下载链接吗 我只会将该数据集用作学术用途 谢谢您 这个是我的学生邮箱：gaozhenwei@std.uestc.edu.cn  谢谢您 这个是我申请的截图 
![76f697e50a5d7270702e1ab4ca5194d140e2b992](https://github.com/user-attachments/assets/8cebdf05-1784-400e-9d9e-1b904c184017)
