### ISSUE TITLE
what is basic?please!!!

### ISSUE THREAD

**Issue by ethan0531** [li-xirong/coco-cn#7]
from basic.constant import ROOT_PATH
NameError: global name 'ROOT_PATH' is not defined

**Comment by yueranjzx** [comment]
'ROOT_PATH' represent the path of your dataset folder, check [setting in coco-cn_caption](https://github.com/li-xirong/coco-cn/blob/master/code/coco-cn_caption/basic/common.py#L7 ) for an example.

**Comment by ethan0531** [comment]
When I ran the program, it defines basic.common.Is this basic.common a library or a written program?(from basic.common import makedirsforfile, checkToSkip, printStatus)Does this basic library need to be installed by yourself？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "li-xirong/coco-cn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 晚上9:58
收件人:&nbsp;"li-xirong/coco-cn"<coco-cn@noreply.github.com&gt;;
抄送:&nbsp;"天亮以后~"<2634966224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [li-xirong/coco-cn] what is basic?please!!! (#7)





 
'ROOT_PATH' represent the path of your dataset folder, check setting in coco-cn_caption for an example.

**Comment by yueranjzx** [comment]
`basic.common` is a written program, if the import path is correct, it will be loaded successfully.
